### PR TITLE
Streamlining Copier Questions/Fixing Linting

### PR DESCRIPTION
**Pull request by theangryangel**
## Description

- Fix line discrep between linting/formatting tools
- :warning: Change the pre-commit excludes question to better suit our needs
- :warning: Remove odoo_listdb, and odoo_dbfilter as we don't use them in dev, and we don't use docker-compose in production
- :warning: Add odoo_admin_password question to aid local dev copies
- :warning: Add a new "What postgres image do you want to use" question. Defaults to standard postgres image (this is backwards compat)

Associated risk level medium

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Suggested UAT/Review Steps

If applicable please list any steps that the end user may require to verify or test the new behaviour.

### CODE REVIEW

**Comment by theangryangel** [comment]
@ellbristow, @jigypeper can you weigh in on this change, specifically the postgres change after the morning standup please?

It's a drop in replacement. However I'm thinking as part of this PR we should also add a question for "standard container or a different container of your choice". This would aid the PGVector work that @jigypeper is working on.

I see this as the last change needed before we push this out to every project.

**Comment by jigypeper** [comment]
Would making the Postgres image with pgvector the standard across board have a huge impact?
Since it's not really there until we add the extension....or is it unnecessary bloat.

**Comment by theangryangel** [comment]
In the past we've pulled in other extensions, PostGIS is a good example.

I'm not sure it's sane to just try and pull in every possible extension we might use, and eventually we'll have to have our own image because it won't be a combination that is officially shipped :(

**Comment by ellbristow** [comment]
Looks fine to me assuming the new postgres image is basically the same thing from another source

**Comment by theangryangel** [comment]
It’s built off the same base, less any tecnatuva customisation, which we don’t use

I’ll add customise the image completely as a question and then I’ll get this rolled out

**Comment by theangryangel** [comment]
Questions added. I need to test it, I'll do it when I get back and then I'll roll it out to us as a starting point, and then on from there.

**Pull request merged**
